name: ModogaKits
version: 0.1
main: main
depend: [ProtocolLib]
author: Kuraceta
commands:
  kit:
  set:
  spawn:
  setarena:
  topkill:
  report:
  admin:
  sc:
  limpar:
  acc:
  stfn:
  bc:
  gamemode:
  gm:
  fly:
  entrar:
  rdm:
  chat:
  youtuber:
  tell:
  simulador:
  skangaroo:
  smonk:
  clan:
  sninja:
  sstomper:
  sswitcher:
  alterar:
  lag:
  ping:
  reiniciar:
  skit:
  tpall:
  tp:
  scoreboard:
  tag:
  aplicar:
  tags:
  r:
  eco:
  npc:
  reloadconfig: